# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="Coldark-Dark"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#313244,bg:#0A0E14,fg:#B3B1AD,fg+:#B3B1AD,hl:#39BAE6,hl+:#39BAE6,pointer:#39BAE6,marker:#AAD94C,spinner:#39BAE6,info:#626A73,header:#626A73,border:#626A73,prompt:#39BAE6,query:#B3B1AD,disabled:#626A73,gutter:#0A0E14,preview-bg:#0A0E14,preview-fg:#B3B1AD,separator:#626A73,label:#39BAE6"
export EZA_COLORS="di=38;2;57;186;230;1:ex=38;2;170;217;76:ln=38;2;149;230;203:fi=0:or=38;2;240;113;120:mi=38;2;240;113;120:da=38;2;98;106;115:sn=38;2;57;186;230:sb=38;2;57;186;230:uu=38;2;98;106;115:un=38;2;98;106;115:gu=38;2;98;106;115:gn=38;2;98;106;115:ga=38;2;170;217;76:gm=38;2;255;180;84:gd=38;2;240;113;120:gv=38;2;255;180;84:gt=38;2;255;143;64:xx=38;2;98;106;115:da=38;2;98;106;115"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;57;186;230m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;255;180;84m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;57;186;230;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;240;113;120'
