#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#0A0E14"

    # Status bar
    [statusbar-bg]="#313244"
    [statusbar-fg]="#B3B1AD"

    # Session (status-left)
    [session-bg]="#39BAE6"
    [session-fg]="#0A0E14"
    [session-prefix-bg]="#F07178"
    [session-copy-bg]="#95E6CB"
    [session-search-bg]="#FFB454"
    [session-command-bg]="#A68EA4"

    # Windows
    [window-active-base]="#39BAE6"
    [window-active-style]="bold"
    [window-inactive-base]="#626A73"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#95E6CB"

    # Panes
    [pane-border-active]="#39BAE6"
    [pane-border-inactive]="#626A73"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#53869B"
    [good-base]="#AAD94C"
    [info-base]="#95E6CB"
    [warning-base]="#FFB454"
    [error-base]="#F07178"
    [disabled-base]="#626A73"

    # Messages
    [message-bg]="#313244"
    [message-fg]="#B3B1AD"

    # Popup & menu
    [popup-bg]="#313244"
    [popup-fg]="#B3B1AD"
    [popup-border]="#39BAE6"
    [menu-bg]="#313244"
    [menu-fg]="#B3B1AD"
    [menu-selected-bg]="#39BAE6"
    [menu-selected-fg]="#0A0E14"
    [menu-border]="#39BAE6"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#FF8F40"
    [magenta]="#A68EA4"
    [surface]="#313244"
)
