//! Theme data for all supported color themes.
//!
//! Each theme provides config snippets for tmux, Vim, Yazi, and lazygit.

use crate::config::{StarshipPreset, Theme};

/// Returns terminal surface colors for tmux panes and app backgrounds.
pub fn terminal_surface_colors(theme: &Theme) -> (&str, &str, &str, &str, String, String) {
    let (bg, fg, accent, _green, _red, _yellow, _orange, _cyan, muted) = theme_palette(theme);
    (
        bg,
        fg,
        accent,
        muted,
        mix_hex_colors(fg, muted, 50),
        mix_hex_colors(accent, fg, 85),
    )
}

/// Subtly dimmed (bg, fg) for *inactive* tmux panes — used by
/// `window-style` so the non-focused panes recede a touch without
/// becoming hard to read.
///
/// Bias is ~12% toward `muted` for both bg and fg, which is enough to
/// be noticeable side-by-side but invisible on a single un-split view.
/// Tuned by eye against the dark themes (where it shows up most) and
/// validated on the light themes (where `muted` darkens both slightly
/// toward grey, still readable).
pub fn dim_inactive_pane_colors(theme: &Theme) -> (String, String) {
    let (bg, fg, _accent, _green, _red, _yellow, _orange, _cyan, muted) = theme_palette(theme);
    let dim_bg = mix_hex_colors(bg, muted, 88);
    let dim_fg = mix_hex_colors(fg, muted, 75);
    (dim_bg, dim_fg)
}

fn mix_hex_colors(primary: &str, secondary: &str, primary_percent: u8) -> String {
    let Some((pr, pg, pb)) = parse_hex_rgb(primary) else {
        return primary.to_string();
    };
    let Some((sr, sg, sb)) = parse_hex_rgb(secondary) else {
        return primary.to_string();
    };
    let p = u16::from(primary_percent.min(100));
    let s = 100 - p;
    let mix = |a: u8, b: u8| -> u8 { ((u16::from(a) * p + u16::from(b) * s) / 100) as u8 };
    format!("#{:02X}{:02X}{:02X}", mix(pr, sr), mix(pg, sg), mix(pb, sb))
}

fn parse_hex_rgb(color: &str) -> Option<(u8, u8, u8)> {
    let hex = color.strip_prefix('#')?;
    if hex.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
    Some((r, g, b))
}

/// Returns the Vim colorscheme name for the given theme.
///
/// Every theme uses the generated `aibox` colorscheme (see
/// [`vim_aibox_colorscheme`]). Vim picks it up from
/// `~/.vim/colors/aibox.vim`, which `seed.rs` materializes from the active
/// palette. This guarantees Vim highlights match Yazi/tmux/Starship colors
/// across all 28 themes, including the ones that previously fell back to
/// `catppuccin_mocha`/`tokyonight`/`gruvbox`.
pub fn vim_colorscheme(_theme: &Theme) -> &'static str {
    "aibox"
}

/// Generate `~/.vim/colors/aibox.vim` content from the theme palette.
pub fn vim_aibox_colorscheme(theme: &Theme) -> String {
    let (bg, fg, accent, green, red, yellow, orange, cyan, muted) = theme_palette(theme);
    let surface = yazi_surface_color(theme);
    let background = vim_background(theme);
    let magenta = mix_hex_colors(red, accent, 60);
    let cursor_line = surface;
    format!(
        r#"" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background={background}

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg={fg}     guibg={bg}     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg={fg}     guibg={bg}
hi LineNr         guifg={muted}  guibg={bg}
hi CursorLineNr   guifg={accent} guibg={cursor_line} gui=bold
hi CursorLine     guibg={cursor_line}
hi CursorColumn   guibg={cursor_line}
hi ColorColumn    guibg={cursor_line}
hi VertSplit      guifg={muted}  guibg={bg}
hi WinSeparator   guifg={muted}  guibg={bg}
hi StatusLine     guifg={bg}     guibg={accent} gui=bold
hi StatusLineNC   guifg={muted}  guibg={surface}
hi TabLine        guifg={muted}  guibg={surface}
hi TabLineFill    guibg={bg}
hi TabLineSel     guifg={bg}     guibg={accent} gui=bold
hi SignColumn     guifg={muted}  guibg={bg}
hi FoldColumn     guifg={muted}  guibg={bg}
hi Folded         guifg={muted}  guibg={surface}
hi NonText        guifg={muted}
hi EndOfBuffer    guifg={bg}     guibg={bg}
hi SpecialKey     guifg={muted}
hi MatchParen     guifg={accent} guibg={surface} gui=bold,underline
hi Conceal        guifg={muted}  guibg={bg}
hi Directory      guifg={accent} gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg={surface}
hi VisualNOS      guibg={surface}
hi Search         guifg={bg}     guibg={yellow} gui=bold
hi IncSearch      guifg={bg}     guibg={orange} gui=bold
hi CurSearch      guifg={bg}     guibg={accent} gui=bold
hi QuickFixLine   guibg={surface} gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg={fg}     guibg={surface}
hi PmenuSel       guifg={bg}     guibg={accent} gui=bold
hi PmenuSbar      guibg={surface}
hi PmenuThumb     guibg={muted}
hi WildMenu       guifg={bg}     guibg={accent} gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg={red}    gui=bold
hi WarningMsg     guifg={yellow}
hi ModeMsg        guifg={accent} gui=bold
hi MoreMsg        guifg={green}
hi Question       guifg={accent}
hi Title          guifg={accent} gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg={muted}    gui=italic
hi Constant       guifg={orange}
hi String         guifg={green}
hi Character      guifg={green}
hi Number         guifg={orange}
hi Boolean        guifg={orange}
hi Float          guifg={orange}
hi Identifier     guifg={fg}
hi Function       guifg={accent}
hi Statement      guifg={red}
hi Conditional    guifg={red}
hi Repeat         guifg={red}
hi Label          guifg={yellow}
hi Operator       guifg={cyan}
hi Keyword        guifg={red}
hi Exception      guifg={red}
hi PreProc        guifg={yellow}
hi Include        guifg={red}
hi Define         guifg={red}
hi Macro          guifg={accent}
hi PreCondit      guifg={yellow}
hi Type           guifg={yellow}
hi StorageClass   guifg={yellow}
hi Structure      guifg={yellow}
hi Typedef        guifg={yellow}
hi Special        guifg={cyan}
hi SpecialChar    guifg={orange}
hi Tag            guifg={accent}
hi Delimiter      guifg={fg}
hi SpecialComment guifg={muted}    gui=italic
hi Debug          guifg={orange}
hi Underlined     guifg={accent}   gui=underline
hi Ignore         guifg={muted}
hi Error          guifg={red}      gui=bold
hi Todo           guifg={yellow}   guibg={surface} gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg={green}    guibg={bg}
hi DiffChange     guifg={yellow}   guibg={bg}
hi DiffDelete     guifg={red}      guibg={bg}
hi DiffText       guifg={accent}   guibg={bg}    gui=bold
hi diffAdded      guifg={green}
hi diffRemoved    guifg={red}
hi diffChanged    guifg={yellow}
hi diffFile       guifg={accent}   gui=bold
hi diffNewFile    guifg={green}    gui=bold
hi diffOldFile    guifg={red}      gui=bold
hi diffLine       guifg={muted}

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp={red}
hi SpellCap       gui=undercurl guisp={yellow}
hi SpellLocal     gui=undercurl guisp={cyan}
hi SpellRare      gui=undercurl guisp={magenta}

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg={green}    guibg={bg}
hi GitGutterChange       guifg={yellow}   guibg={bg}
hi GitGutterDelete       guifg={red}      guibg={bg}
hi GitGutterChangeDelete guifg={orange}   guibg={bg}
hi SignifySignAdd        guifg={green}    guibg={bg}
hi SignifySignChange     guifg={yellow}   guibg={bg}
hi SignifySignDelete     guifg={red}      guibg={bg}

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg={cyan}  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg={muted}    guibg={bg}
hi NormalFloat    guifg={fg}       guibg={surface}
"#
    )
}

/// Returns the Vim background setting (dark/light).
pub fn vim_background(theme: &Theme) -> &'static str {
    match theme {
        Theme::GruvboxLight
        | Theme::CatppuccinLatte
        | Theme::TokyoNightDay
        | Theme::RosePineDawn
        | Theme::MaterialLighter
        | Theme::SolarizedLight
        | Theme::GithubLight
        | Theme::AyuLight
        | Theme::NightOwlLight => "light",
        _ => "dark",
    }
}

/// Returns the Yazi theme.toml content for the given theme.
///
/// Generated entirely from the 9-slot palette so every aibox theme renders
/// consistently in Yazi (status bar, mode, tabs, popup pickers, filetype
/// colors) without relying on bundled per-theme toml files.
/// Yazi tab separator open/close glyphs for a given tmux separator style.
/// Keeps the file manager's tab chevrons in lockstep with the status-bar style.
pub fn yazi_tab_separators(style: &str) -> (&'static str, &'static str) {
    match style {
        "normal" => ("", ""),
        "rounded" => ("", ""),
        "slant" => ("", ""),
        "slantup" => ("", ""),
        "flame" => ("", ""),
        "pixel" => ("▕", "▏"),
        "none" => ("", ""),
        // trapezoid / honeycomb / unknown — fall back to chevrons
        _ => ("", ""),
    }
}

/// Returns the Yazi theme.toml content for the given theme + tmux separator
/// style. The style argument lets Yazi's tab chevrons mirror the tmux status
/// bar's `@powerkit_separator_style`.
pub fn yazi_theme_with_separator(theme: &Theme, sep_style: &str) -> String {
    let (bg, fg, accent, green, red, yellow, orange, cyan, muted) = theme_palette(theme);
    let surface = yazi_surface_color(theme);
    let (sep_open, sep_close) = yazi_tab_separators(sep_style);
    // Derive a magenta/pink slot for marker_copied / image-file hue without
    // adding a 10th palette entry — mix accent and red, biased toward red.
    let magenta = mix_hex_colors(red, accent, 60);
    format!(
        r#"# =============================================================================
# Yazi theme — generated by aibox CLI from the active theme palette
# Docs: https://yazi-rs.github.io/docs/configuration/theme
# =============================================================================

[mgr]
cwd = {{ fg = "{accent}" }}
hovered = {{ fg = "{bg}", bg = "{fg}" }}
preview_hovered = {{ bg = "{surface}", underline = true }}
find_keyword = {{ fg = "{yellow}", bold = true }}
find_position = {{ fg = "{magenta}", italic = true }}
marker_selected = {{ fg = "{green}", bg = "{green}" }}
marker_copied = {{ fg = "{accent}", bg = "{accent}" }}
marker_cut = {{ fg = "{red}", bg = "{red}" }}

[tabs]
active = {{ fg = "{bg}", bg = "{accent}", bold = true }}
inactive = {{ fg = "{muted}", bg = "{surface}" }}
sep_inner = {{ open = "{sep_open}", close = "{sep_close}" }}
sep_outer = {{ open = "{sep_open}", close = "{sep_close}" }}

[mode]
normal_main = {{ fg = "{bg}", bg = "{green}", bold = true }}
normal_alt = {{ fg = "{green}", bg = "{surface}", bold = true }}
select_main = {{ fg = "{bg}", bg = "{accent}", bold = true }}
select_alt = {{ fg = "{accent}", bg = "{surface}", bold = true }}
unset_main = {{ fg = "{bg}", bg = "{magenta}", bold = true }}
unset_alt = {{ fg = "{magenta}", bg = "{surface}", bold = true }}

[status]
overall = {{ fg = "{fg}", bg = "{surface}" }}
sep_left = {{ open = "{sep_open}", close = "{sep_close}" }}
sep_right = {{ open = "{sep_open}", close = "{sep_close}" }}
perm_type = {{ fg = "{accent}" }}
perm_read = {{ fg = "{yellow}" }}
perm_write = {{ fg = "{red}" }}
perm_exec = {{ fg = "{green}" }}
perm_sep = {{ fg = "{muted}" }}
progress_label = {{ fg = "{fg}", bold = true }}
progress_normal = {{ fg = "{accent}", bg = "{surface}" }}
progress_error = {{ fg = "{red}", bg = "{surface}" }}

[input]
border = {{ fg = "{accent}" }}
title = {{ fg = "{accent}", bg = "{bg}", bold = true }}
value = {{ fg = "{fg}", bg = "{bg}" }}
selected = {{ reversed = true }}

[pick]
border = {{ fg = "{accent}" }}
active = {{ fg = "{magenta}" }}
inactive = {{ fg = "{muted}", bg = "{bg}" }}

[cmp]
border = {{ fg = "{accent}" }}
active = {{ fg = "{magenta}" }}
inactive = {{ fg = "{muted}", bg = "{bg}" }}

[tasks]
border = {{ fg = "{accent}" }}
title = {{ fg = "{accent}", bg = "{bg}", bold = true }}
hovered = {{ bg = "{surface}", underline = true }}

[which]
mask = {{ bg = "{surface}" }}
cand = {{ fg = "{cyan}" }}
rest = {{ fg = "{muted}" }}
desc = {{ fg = "{magenta}" }}
separator = "  "
separator_style = {{ fg = "{muted}" }}

[help]
on = {{ fg = "{cyan}" }}
run = {{ fg = "{magenta}" }}
desc = {{ fg = "{fg}", bg = "{bg}" }}
hovered = {{ bg = "{surface}", bold = true }}
footer = {{ fg = "{bg}", bg = "{fg}" }}

[git]
modified = {{ fg = "{yellow}" }}
untracked = {{ fg = "{magenta}" }}
added = {{ fg = "{green}" }}
deleted = {{ fg = "{red}" }}
updated = {{ fg = "{accent}" }}
ignored = {{ fg = "{muted}" }}

[filetype]
rules = [
    {{ url = "*/", fg = "{accent}", bold = true }},
    {{ url = "*.rs", fg = "{orange}" }},
    {{ url = "*.py", fg = "{yellow}" }},
    {{ url = "*.js", fg = "{yellow}" }},
    {{ url = "*.ts", fg = "{accent}" }},
    {{ url = "*.sh", fg = "{green}" }},
    {{ url = "*.toml", fg = "{cyan}" }},
    {{ url = "*.yaml", fg = "{cyan}" }},
    {{ url = "*.yml", fg = "{cyan}" }},
    {{ url = "*.json", fg = "{cyan}" }},
    {{ url = "*.kdl", fg = "{cyan}" }},
    {{ url = "*.html", fg = "{orange}" }},
    {{ url = "*.css", fg = "{accent}" }},
    {{ url = "*.md", fg = "{fg}" }},
    {{ url = "*.tex", fg = "{green}" }},
    {{ url = "*.typ", fg = "{green}" }},
    {{ url = "*.pdf", fg = "{red}" }},
    {{ url = "*.png", fg = "{magenta}" }},
    {{ url = "*.jpg", fg = "{magenta}" }},
    {{ url = "*.jpeg", fg = "{magenta}" }},
    {{ url = "*.gif", fg = "{magenta}" }},
    {{ url = "*.svg", fg = "{magenta}" }},
    {{ url = "*.zip", fg = "{orange}" }},
    {{ url = "*.tar*", fg = "{orange}" }},
    {{ url = "*.gz", fg = "{orange}" }},
    {{ url = "*.gitignore", fg = "{muted}" }},
    {{ url = ".env*", fg = "{red}" }},
    {{ url = "Dockerfile*", fg = "{accent}" }},
    {{ url = "Makefile", fg = "{green}" }},
    {{ url = "Cargo.toml", fg = "{orange}", bold = true }},
    {{ url = "Cargo.lock", fg = "{muted}" }},
]
"#
    )
}

fn yazi_surface_color(theme: &Theme) -> &'static str {
    match theme {
        Theme::GruvboxLight => "#EBDBB2",
        Theme::CatppuccinLatte
        | Theme::TokyoNightDay
        | Theme::RosePineDawn
        | Theme::MaterialLighter
        | Theme::SolarizedLight
        | Theme::GithubLight
        | Theme::AyuLight
        | Theme::NightOwlLight => "#CCD0DA",
        Theme::GruvboxDark => "#3C3836",
        Theme::Nord => "#3B4252",
        Theme::Dracula => "#44475A",
        Theme::TokyoNight | Theme::TokyoNightStorm | Theme::Moonlight => "#283457",
        Theme::Projectious => "#131E2B",
        _ => "#313244",
    }
}

/// Returns the lazygit theme YAML snippet (gui.theme section).
pub fn lazygit_theme(theme: &Theme) -> String {
    let (bg, fg, accent, _green, red, yellow, _orange, cyan, muted) = theme_palette(theme);
    format!(
        r#"gui:
  theme:
    activeBorderColor:
      - '{accent}'
      - bold
    inactiveBorderColor:
      - '{muted}'
    optionsTextColor:
      - '{cyan}'
    selectedLineBgColor:
      - '{bg}'
    cherryPickedCommitBgColor:
      - '{muted}'
    cherryPickedCommitFgColor:
      - '{accent}'
    unstagedChangesColor:
      - '{red}'
    defaultFgColor:
      - '{fg}'
    searchingActiveBorderColor:
      - '{yellow}'
"#
    )
}

/// Color palette values for Starship prompt theming.
fn theme_palette(theme: &Theme) -> (&str, &str, &str, &str, &str, &str, &str, &str, &str) {
    // Returns (bg, fg, accent, green, red, yellow, orange, cyan, muted)
    match theme {
        Theme::GruvboxDark => (
            "#282828", "#D5C4A1", "#D79921", "#98971A", "#CC241D", "#D79921", "#D65D0E", "#689D6A",
            "#928374",
        ),
        Theme::GruvboxLight => (
            "#FBF1C7", "#3C3836", "#D65D0E", "#79740E", "#CC241D", "#B57614", "#D65D0E", "#076678",
            "#928374",
        ),
        Theme::CatppuccinMocha => (
            "#1E1E2E", "#CDD6F4", "#89B4FA", "#A6E3A1", "#F38BA8", "#F9E2AF", "#FAB387", "#94E2D5",
            "#6C7086",
        ),
        Theme::CatppuccinMacchiato => (
            "#24273A", "#CAD3F5", "#8AADF4", "#A6DA95", "#ED8796", "#EED49F", "#F5A97F", "#8BD5CA",
            "#6E738D",
        ),
        Theme::CatppuccinFrappe => (
            "#303446", "#C6D0F5", "#8CAAEE", "#A6D189", "#E78284", "#E5C890", "#EF9F76", "#81C8BE",
            "#737994",
        ),
        Theme::CatppuccinLatte => (
            "#EFF1F5", "#4C4F69", "#1E66F5", "#40A02B", "#D20F39", "#DF8E1D", "#FE640B", "#179299",
            "#9CA0B0",
        ),
        Theme::Dracula => (
            "#282A36", "#F8F8F2", "#BD93F9", "#50FA7B", "#FF5555", "#F1FA8C", "#FFB86C", "#8BE9FD",
            "#6272A4",
        ),
        Theme::TokyoNight => (
            "#1A1B26", "#C0CAF5", "#7AA2F7", "#9ECE6A", "#F7768E", "#E0AF68", "#FF9E64", "#7DCFFF",
            "#565F89",
        ),
        Theme::TokyoNightStorm => (
            "#24283B", "#C0CAF5", "#7AA2F7", "#9ECE6A", "#F7768E", "#E0AF68", "#FF9E64", "#7DCFFF",
            "#565F89",
        ),
        Theme::TokyoNightDay => (
            "#E1E2E7", "#3760BF", "#2E7DE9", "#587539", "#F52A65", "#8C6C3E", "#B15C00", "#007197",
            "#7B8496",
        ),
        Theme::Nord => (
            "#2E3440", "#D8DEE9", "#88C0D0", "#A3BE8C", "#BF616A", "#EBCB8B", "#D08770", "#81A1C1",
            "#4C566A",
        ),
        Theme::RosePine => (
            "#191724", "#E0DEF4", "#C4A7E7", "#31748F", "#EB6F92", "#F6C177", "#EA9A97", "#9CCFD8",
            "#6E6A86",
        ),
        Theme::RosePineMoon => (
            "#232136", "#E0DEF4", "#C4A7E7", "#3E8FB0", "#EB6F92", "#F6C177", "#EA9A97", "#9CCFD8",
            "#6E6A86",
        ),
        Theme::RosePineDawn => (
            "#FAF4ED", "#575279", "#907AA9", "#56949F", "#B4637A", "#EA9D34", "#D7827E", "#286983",
            "#9893A5",
        ),
        Theme::Material => (
            "#263238", "#EEFFFF", "#82AAFF", "#C3E88D", "#F07178", "#FFCB6B", "#F78C6C", "#89DDFF",
            "#546E7A",
        ),
        Theme::MaterialOcean => (
            "#0F111A", "#A6ACCD", "#82AAFF", "#C3E88D", "#F07178", "#FFCB6B", "#F78C6C", "#89DDFF",
            "#464B5D",
        ),
        Theme::MaterialPalenight => (
            "#292D3E", "#A6ACCD", "#82AAFF", "#C3E88D", "#F07178", "#FFCB6B", "#F78C6C", "#89DDFF",
            "#676E95",
        ),
        Theme::MaterialLighter => (
            "#FAFAFA", "#546E7A", "#6182B8", "#91B859", "#E53935", "#F6A434", "#F76D47", "#39ADB5",
            "#90A4AE",
        ),
        Theme::SolarizedDark => (
            "#002B36", "#93A1A1", "#268BD2", "#859900", "#DC322F", "#B58900", "#CB4B16", "#2AA198",
            "#657B83",
        ),
        Theme::SolarizedLight => (
            "#FDF6E3", "#586E75", "#268BD2", "#859900", "#DC322F", "#B58900", "#CB4B16", "#2AA198",
            "#93A1A1",
        ),
        Theme::GithubDark => (
            "#0D1117", "#C9D1D9", "#58A6FF", "#3FB950", "#F85149", "#D29922", "#DB6D28", "#79C0FF",
            "#8B949E",
        ),
        Theme::GithubLight => (
            "#FFFFFF", "#24292F", "#0969DA", "#1A7F37", "#CF222E", "#9A6700", "#BC4C00", "#218BFF",
            "#6E7781",
        ),
        Theme::AyuDark => (
            "#0A0E14", "#B3B1AD", "#39BAE6", "#AAD94C", "#F07178", "#FFB454", "#FF8F40", "#95E6CB",
            "#626A73",
        ),
        Theme::AyuMirage => (
            "#1F2430", "#CCCAC2", "#5CCFE6", "#BAE67E", "#F28779", "#FFD173", "#FFAD66", "#95E6CB",
            "#707A8C",
        ),
        Theme::AyuLight => (
            "#FAFAFA", "#5C6773", "#55B4D4", "#86B300", "#E7676A", "#FA8D3E", "#F07171", "#4CBF99",
            "#ABB0B6",
        ),
        Theme::NightOwl => (
            "#011627", "#D6DEEB", "#82AAFF", "#22DA6E", "#EF5350", "#C5E478", "#F78C6C", "#21C7A8",
            "#637777",
        ),
        Theme::NightOwlLight => (
            "#FBFBFB", "#403F53", "#4876D6", "#2AA298", "#D3423E", "#DAA520", "#DD6A58", "#08916A",
            "#989FB1",
        ),
        Theme::Moonlight => (
            "#212337", "#C8D3F5", "#82AAFF", "#C3E88D", "#FF757F", "#FFC777", "#F78C6C", "#86E1FC",
            "#7A88CF",
        ),
        Theme::Projectious => (
            "#0E1720", "#C5DAF0", "#E05232", "#4FB07A", "#E55B5B", "#E0B85B", "#F2A65A", "#8AACC8",
            "#7B8DA3",
        ),
    }
}

/// Generate starship.toml content for the given preset and theme.
pub fn starship_config(preset: &StarshipPreset, theme: &Theme) -> String {
    let (bg, fg, accent, green, red, yellow, orange, cyan, muted) = theme_palette(theme);

    match preset {
        StarshipPreset::Default => format!(
            r#"# aibox starship config — default preset
palette = "aibox"

format = "$directory$git_branch$git_status$python$rust$nodejs$golang$cmd_duration$line_break$character"

[directory]
style = "bold fg:{accent}"
truncation_length = 3

[git_branch]
style = "fg:{green}"

[git_status]
style = "fg:{accent}"

[python]
style = "fg:{yellow}"
format = "[$symbol$version]($style) "

[rust]
style = "fg:{orange}"
format = "[$symbol$version]($style) "

[nodejs]
style = "fg:{green}"
format = "[$symbol$version]($style) "

[golang]
style = "fg:{cyan}"
format = "[$symbol$version]($style) "

[cmd_duration]
style = "fg:{muted}"
min_time = 2_000

[character]
success_symbol = "[❯](bold fg:{green})"
error_symbol = "[❯](bold fg:{red})"

[palettes.aibox]
bg = "{bg}"
fg = "{fg}"
accent = "{accent}"
"#
        ),

        StarshipPreset::Plain => format!(
            r#"# aibox starship config — plain preset (no Nerd Font needed)
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
style = "bold fg:{accent}"

[git_branch]
symbol = ""
style = "fg:{green}"

[git_status]
style = "fg:{accent}"

[character]
success_symbol = "[>](bold fg:{green})"
error_symbol = "[>](bold fg:{red})"

[python]
symbol = "py "
[rust]
symbol = "rs "
[nodejs]
symbol = "js "
[golang]
symbol = "go "
"#
        ),

        StarshipPreset::Minimal => format!(
            r#"# aibox starship config — minimal preset
format = "$directory$git_branch$line_break$character"

[directory]
style = "bold fg:{accent}"
truncation_length = 2

[git_branch]
style = "fg:{green}"
format = " [$branch]($style)"

[character]
success_symbol = "[❯](fg:{accent})"
error_symbol = "[❯](bold fg:{red})"
"#
        ),

        StarshipPreset::NerdFont => format!(
            r#"# aibox starship config — nerd-font preset
palette = "aibox"

format = "$os$directory$git_branch$git_status$python$rust$nodejs$golang$docker_context$cmd_duration$line_break$character"

[os]
disabled = false
style = "fg:{fg}"

[directory]
style = "bold fg:{accent}"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "fg:{green}"

[git_status]
style = "fg:{accent}"

[python]
symbol = " "
[rust]
symbol = " "
[nodejs]
symbol = " "
[golang]
symbol = " "
[docker_context]
symbol = " "

[cmd_duration]
style = "fg:{muted}"

[character]
success_symbol = "[❯](bold fg:{green})"
error_symbol = "[❯](bold fg:{red})"

[palettes.aibox]
bg = "{bg}"
fg = "{fg}"
accent = "{accent}"
"#
        ),

        StarshipPreset::Pastel | StarshipPreset::PastelPowerline => format!(
            r#"# aibox starship config — pastel powerline preset
# One-line prompt inspired by https://starship.rs/presets/#pastel-powerline.
palette = "aibox"

format = """
[](fg:{accent})\
$directory\
[](fg:{accent} bg:{green})\
$git_branch\
$git_status\
[](fg:{green} bg:{orange})\
$python\
$rust\
$nodejs\
$golang\
[](fg:{orange} bg:{bg})\
$cmd_duration\
$character"""

[directory]
style = "bold bg:{accent} fg:{bg}"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bg:{green} fg:{bg}"
symbol = " "
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:{green} fg:{bg}"
format = "[$all_status$ahead_behind ]($style)"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
modified = "!$count"
staged = "+$count"
untracked = "?$count"

[python]
style = "bg:{orange} fg:{bg}"
format = "[ $symbol$version ]($style)"
[rust]
style = "bg:{orange} fg:{bg}"
format = "[ $symbol$version ]($style)"
[nodejs]
style = "bg:{orange} fg:{bg}"
format = "[ $symbol$version ]($style)"
[golang]
style = "bg:{orange} fg:{bg}"
format = "[ $symbol$version ]($style)"

[cmd_duration]
style = "fg:{muted}"
min_time = 2_000
format = "[ $duration ]($style)"

[character]
success_symbol = "[❯](bold fg:{accent}) "
error_symbol = "[❯](bold fg:{red}) "

[palettes.aibox]
bg = "{bg}"
fg = "{fg}"
accent = "{accent}"
"#
        ),

        StarshipPreset::Bracketed => format!(
            r#"# aibox starship config — bracketed segments preset
format = "$directory$git_branch$git_status$python$rust$nodejs$golang$cmd_duration$line_break$character"

[directory]
style = "fg:{accent}"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "fg:{green}"
format = "[\\[$branch\\]]($style) "

[git_status]
style = "fg:{accent}"
format = "[\\[$all_status$ahead_behind\\]]($style) "

[python]
format = "[\\[$symbol$version\\]](fg:{yellow}) "
[rust]
format = "[\\[$symbol$version\\]](fg:{orange}) "
[nodejs]
format = "[\\[$symbol$version\\]](fg:{green}) "
[golang]
format = "[\\[$symbol$version\\]](fg:{cyan}) "

[cmd_duration]
format = "[\\[$duration\\]](fg:{muted}) "

[character]
success_symbol = "[❯](bold fg:{green})"
error_symbol = "[❯](bold fg:{red})"
"#
        ),

        StarshipPreset::Arrow => format!(
            r#"# aibox starship config — arrow preset (powerline chevron/airline style)
# Requires a Nerd Font or Powerline-patched font for the arrow separators (e0b0/e0b2).
palette = "aibox"

format = """
[](fg:{accent})\
$directory\
[](fg:{accent} bg:{green})\
$git_branch\
$git_status\
[](fg:{green} bg:{bg})\
 $cmd_duration\
$line_break\
$character"""

[directory]
style = "bold bg:{accent} fg:{bg}"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bg:{green} fg:{bg}"
symbol = " "
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:{green} fg:{bg}"
format = "[$all_status$ahead_behind]($style)"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
modified = "!$count"
staged = "+$count"
untracked = "?$count"

[cmd_duration]
style = "fg:{muted}"
min_time = 2_000
format = "[ $duration]($style)"

[character]
success_symbol = "[❯](bold fg:{accent})"
error_symbol = "[❯](bold fg:{red})"

[python]
style = "fg:{yellow}"
format = "[$symbol$version]($style) "
[rust]
style = "fg:{orange}"
format = "[$symbol$version]($style) "
[nodejs]
style = "fg:{green}"
format = "[$symbol$version]($style) "
[golang]
style = "fg:{cyan}"
format = "[$symbol$version]($style) "

[palettes.aibox]
bg = "{bg}"
fg = "{fg}"
accent = "{accent}"
"#
        ),
    }
}

/// Map an aibox theme to a `bat` built-in syntax theme.
///
/// `bat --list-themes` shows the supported set; Catppuccin variants ship in
/// recent bat versions. Light themes return `*-light` variants so plain-text
/// output stays legible on pale backgrounds.
pub fn bat_theme(theme: &Theme) -> &'static str {
    match theme {
        Theme::GruvboxDark => "gruvbox-dark",
        Theme::GruvboxLight => "gruvbox-light",
        Theme::CatppuccinMocha => "Catppuccin Mocha",
        Theme::CatppuccinMacchiato => "Catppuccin Macchiato",
        Theme::CatppuccinFrappe => "Catppuccin Frappe",
        Theme::CatppuccinLatte => "Catppuccin Latte",
        Theme::Dracula => "Dracula",
        Theme::TokyoNight | Theme::TokyoNightStorm | Theme::Moonlight => "Coldark-Dark",
        Theme::TokyoNightDay => "Coldark-Cold",
        Theme::Nord => "Nord",
        Theme::RosePine | Theme::RosePineMoon => "Catppuccin Mocha",
        Theme::RosePineDawn => "Catppuccin Latte",
        Theme::Material | Theme::MaterialOcean | Theme::MaterialPalenight => "Coldark-Dark",
        Theme::MaterialLighter => "Coldark-Cold",
        Theme::SolarizedDark => "Solarized (dark)",
        Theme::SolarizedLight => "Solarized (light)",
        Theme::GithubDark => "Visual Studio Dark+",
        Theme::GithubLight => "GitHub",
        Theme::AyuDark | Theme::AyuMirage => "Coldark-Dark",
        Theme::AyuLight => "Coldark-Cold",
        Theme::NightOwl => "Coldark-Dark",
        Theme::NightOwlLight => "Coldark-Cold",
        Theme::Projectious => "Coldark-Dark",
    }
}

/// `delta` `syntax-theme` value — matches `bat_theme` since delta consumes bat themes.
pub fn delta_syntax_theme(theme: &Theme) -> &'static str {
    bat_theme(theme)
}

/// Lnav built-in theme name. Lnav ships: default, eldar, grayscale, monocai,
/// night-owl, solarized-dark, solarized-light, dracula, tokyo-night.
pub fn lnav_theme(theme: &Theme) -> &'static str {
    match theme {
        Theme::SolarizedLight
        | Theme::CatppuccinLatte
        | Theme::GruvboxLight
        | Theme::RosePineDawn
        | Theme::MaterialLighter
        | Theme::GithubLight
        | Theme::AyuLight
        | Theme::TokyoNightDay
        | Theme::NightOwlLight => "solarized-light",
        Theme::SolarizedDark => "solarized-dark",
        Theme::Dracula => "dracula",
        Theme::NightOwl => "night-owl",
        Theme::TokyoNight | Theme::TokyoNightStorm | Theme::Moonlight | Theme::Projectious => {
            "tokyo-night"
        }
        _ => "monocai",
    }
}

/// fzf `--color` clause string (without the leading `--color=`).
pub fn fzf_color_spec(theme: &Theme) -> String {
    let (bg, fg, accent, green, _red, yellow, _orange, _cyan, muted) = theme_palette(theme);
    // Reuse the yazi surface for the selected-row background so hover state
    // matches the file manager.
    let surface = yazi_surface_color(theme);
    format!(
        "bg+:{surface},bg:{bg},fg:{fg},fg+:{fg},hl:{accent},hl+:{accent},\
pointer:{accent},marker:{green},spinner:{accent},info:{muted},header:{muted},\
border:{muted},prompt:{accent},query:{fg},disabled:{muted},gutter:{bg},\
preview-bg:{bg},preview-fg:{fg},separator:{muted},label:{accent},\
nth:{yellow}"
    )
}

/// EZA_COLORS env value. The format is a colon-separated list of `key=spec`
/// items where `spec` is an ANSI SGR sequence. We map a small but visible set
/// of file categories to palette slots so `ls` output coheres with the rest.
pub fn eza_colors_spec(theme: &Theme) -> String {
    let (_bg, _fg, accent, green, red, yellow, orange, cyan, muted) = theme_palette(theme);
    let a = hex_to_sgr_fg(accent);
    let g = hex_to_sgr_fg(green);
    let r = hex_to_sgr_fg(red);
    let y = hex_to_sgr_fg(yellow);
    let o = hex_to_sgr_fg(orange);
    let c = hex_to_sgr_fg(cyan);
    let m = hex_to_sgr_fg(muted);
    // di=directory, ex=executable, ln=symlink, fi=regular file, *.rs/*.py etc.
    // git/perm columns and size units use accent/muted to match the prompt.
    format!(
        "di={a};1:ex={g}:ln={c}:fi=0:or={r}:mi={r}:\
da={m}:sn={a}:sb={a}:uu={m}:un={m}:gu={m}:gn={m}:\
ga={g}:gm={y}:gd={r}:gv={y}:gt={o}:\
xx={m}:da={m}"
    )
}

fn hex_to_sgr_fg(hex: &str) -> String {
    if let Some((r, g, b)) = parse_hex_rgb(hex) {
        format!("38;2;{r};{g};{b}")
    } else {
        "0".to_string()
    }
}

/// Generate `~/.config/aibox/theme-env.sh` content: exports BAT_THEME,
/// FZF_DEFAULT_OPTS, EZA_COLORS, LESS_TERMCAP_*, and a few helper LS_COLORS
/// hints. Sourced from `~/.bashrc` if present.
pub fn theme_env_script(theme: &Theme) -> String {
    let bat = bat_theme(theme);
    let fzf = fzf_color_spec(theme);
    let eza = eza_colors_spec(theme);
    let (_bg, _fg, accent, _green, red, yellow, _orange, _cyan, _muted) = theme_palette(theme);
    let acc = hex_to_sgr_fg(accent);
    let yel = hex_to_sgr_fg(yellow);
    let red = hex_to_sgr_fg(red);
    format!(
        r#"# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="{bat}"
export FZF_DEFAULT_OPTS="${{FZF_DEFAULT_OPTS:-}} --color={fzf}"
export EZA_COLORS="{eza}"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[{acc}m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[{yel}m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[{acc};7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='{red}'
"#
    )
}

/// Generate `~/.config/lnav/config.json` content: pins lnav to the closest
/// matching built-in theme.
pub fn lnav_config(theme: &Theme) -> String {
    let name = lnav_theme(theme);
    format!(
        r#"{{
  "$schema": "https://lnav.org/schemas/config-v1.schema.json",
  "ui": {{
    "theme": "{name}"
  }}
}}
"#
    )
}

/// Generate a tmux-powerkit custom theme file from the aibox palette.
///
/// Loaded by powerkit via `@powerkit_theme "custom"` +
/// `@powerkit_custom_theme_path`. Producing this file ourselves means the
/// status-bar chevron separators always end on the exact background color
/// aibox already uses — no more "strange colored separators" when the upstream
/// powerkit theme variant doesn't quite match our palette (Projectious in
/// particular previously fell back to tokyo-night and rendered chevrons in
/// tokyo-night's bg).
pub fn tmux_powerkit_custom_theme(theme: &Theme) -> String {
    let (bg, fg, accent, green, red, yellow, orange, cyan, muted) = theme_palette(theme);
    let surface = yazi_surface_color(theme);
    let magenta = mix_hex_colors(red, accent, 60);
    // A "neutral OK" tone: muted accent — keeps non-warning segments calm
    // without making them disappear against the surface.
    let ok = mix_hex_colors(accent, muted, 35);
    format!(
        r#"#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="{bg}"

    # Status bar
    [statusbar-bg]="{surface}"
    [statusbar-fg]="{fg}"

    # Session (status-left)
    [session-bg]="{accent}"
    [session-fg]="{bg}"
    [session-prefix-bg]="{red}"
    [session-copy-bg]="{cyan}"
    [session-search-bg]="{yellow}"
    [session-command-bg]="{magenta}"

    # Windows
    [window-active-base]="{accent}"
    [window-active-style]="bold"
    [window-inactive-base]="{muted}"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="{cyan}"

    # Panes
    [pane-border-active]="{accent}"
    [pane-border-inactive]="{muted}"

    # Health / state segments (chevron color rotation source)
    [ok-base]="{ok}"
    [good-base]="{green}"
    [info-base]="{cyan}"
    [warning-base]="{yellow}"
    [error-base]="{red}"
    [disabled-base]="{muted}"

    # Messages
    [message-bg]="{surface}"
    [message-fg]="{fg}"

    # Popup & menu
    [popup-bg]="{surface}"
    [popup-fg]="{fg}"
    [popup-border]="{accent}"
    [menu-bg]="{surface}"
    [menu-fg]="{fg}"
    [menu-selected-bg]="{accent}"
    [menu-selected-fg]="{bg}"
    [menu-border]="{accent}"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="{orange}"
    [magenta]="{magenta}"
    [surface]="{surface}"
)
"#
    )
}

/// Whether the theme is best rendered with a dark or light TUI background.
pub fn is_light_theme(theme: &Theme) -> bool {
    matches!(vim_background(theme), "light")
}

/// Claude Code `~/.claude/settings.json` `theme` field.
/// Claude supports: "dark", "light", "dark-daltonized", "light-daltonized",
/// "dark-ansi", "light-ansi", "system". We map to light/dark only.
pub fn claude_theme(theme: &Theme) -> &'static str {
    if is_light_theme(theme) {
        "light"
    } else {
        "dark"
    }
}

/// Aider `code-theme` (a Pygments style). Aider does NOT understand most named
/// theme palettes; it picks a code-highlight Pygments theme + a dark/light
/// background flag. We map to the closest Pygments style.
pub fn aider_code_theme(theme: &Theme) -> &'static str {
    match theme {
        Theme::GruvboxDark | Theme::GruvboxLight => "gruvbox-dark",
        Theme::SolarizedDark => "solarized-dark",
        Theme::SolarizedLight => "solarized-light",
        Theme::Dracula => "dracula",
        Theme::GithubDark => "github-dark",
        Theme::GithubLight => "default",
        Theme::Nord => "nord",
        Theme::CatppuccinLatte
        | Theme::TokyoNightDay
        | Theme::RosePineDawn
        | Theme::MaterialLighter
        | Theme::AyuLight
        | Theme::NightOwlLight => "default",
        _ => "monokai",
    }
}

/// Gemini CLI `~/.gemini/settings.json` `theme` value. Gemini ships a fixed
/// set of named themes. We map each aibox theme to its closest match.
pub fn gemini_theme(theme: &Theme) -> &'static str {
    match theme {
        Theme::Dracula => "Dracula",
        Theme::GithubDark => "GitHub",
        Theme::GithubLight => "GitHub Light",
        Theme::AyuDark | Theme::AyuMirage => "Ayu",
        Theme::AyuLight => "Ayu Light",
        Theme::CatppuccinLatte
        | Theme::GruvboxLight
        | Theme::TokyoNightDay
        | Theme::RosePineDawn
        | Theme::MaterialLighter
        | Theme::SolarizedLight
        | Theme::NightOwlLight => "Default Light",
        Theme::NightOwl => "Atom One Dark",
        _ => "Default",
    }
}

/// OpenCode `~/.config/opencode/opencode.json` (or `~/.opencode/opencode.json`)
/// `theme` value. OpenCode supports: system, opencode, tokyonight, everforest,
/// ayu, catppuccin, dracula, gruvbox, kanagawa, matrix, monokai, nord,
/// onedark, rose-pine.
pub fn opencode_theme(theme: &Theme) -> &'static str {
    match theme {
        Theme::GruvboxDark | Theme::GruvboxLight => "gruvbox",
        Theme::CatppuccinMocha
        | Theme::CatppuccinMacchiato
        | Theme::CatppuccinFrappe
        | Theme::CatppuccinLatte => "catppuccin",
        Theme::Dracula => "dracula",
        Theme::TokyoNight | Theme::TokyoNightStorm | Theme::TokyoNightDay | Theme::Moonlight => {
            "tokyonight"
        }
        Theme::Nord => "nord",
        Theme::RosePine | Theme::RosePineMoon | Theme::RosePineDawn => "rose-pine",
        Theme::Material
        | Theme::MaterialOcean
        | Theme::MaterialPalenight
        | Theme::MaterialLighter => "onedark",
        Theme::AyuDark | Theme::AyuMirage | Theme::AyuLight => "ayu",
        Theme::GithubDark | Theme::GithubLight => "opencode",
        Theme::SolarizedDark | Theme::SolarizedLight => "opencode",
        Theme::NightOwl | Theme::NightOwlLight => "tokyonight",
        Theme::Projectious => "tokyonight",
    }
}

/// Git config snippet that wires up delta as the diff/log/show pager. Emitted
/// in place of the previous minimal gitconfig so `git diff`, `git log -p` and
/// lazygit hunks all render with theme-matched syntax highlighting.
pub fn gitconfig_with_delta(theme: &Theme) -> String {
    let (_bg, _fg, accent, _green, _red, _yellow, _orange, _cyan, muted) = theme_palette(theme);
    let syntax = delta_syntax_theme(theme);
    let dark = matches!(vim_background(theme), "dark");
    let light_flag = if dark { "false" } else { "true" };
    format!(
        r##"[core]
    editor = vim
    pager = delta
[init]
    defaultBranch = main
[pull]
    rebase = true
[interactive]
    diffFilter = delta --color-only
[delta]
    syntax-theme = {syntax}
    light = {light_flag}
    navigate = true
    line-numbers = true
    side-by-side = false
    hunk-header-decoration-style = "{muted}" box
    file-decoration-style = "{accent}" ul
    minus-style = syntax "#3B1F22"
    minus-emph-style = syntax "#6B1E25"
    plus-style = syntax "#1F3B25"
    plus-emph-style = syntax "#1F5B33"
    zero-style = syntax
[merge]
    conflictStyle = zdiff3
"##
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::StarshipPreset;

    /// Every theme this crate exposes, used by the matrix tests below to
    /// guarantee no variant silently regresses.
    const ALL_THEMES: &[Theme] = &[
        Theme::GruvboxDark,
        Theme::GruvboxLight,
        Theme::CatppuccinMocha,
        Theme::CatppuccinMacchiato,
        Theme::CatppuccinFrappe,
        Theme::CatppuccinLatte,
        Theme::Dracula,
        Theme::TokyoNight,
        Theme::TokyoNightStorm,
        Theme::TokyoNightDay,
        Theme::Nord,
        Theme::RosePine,
        Theme::RosePineMoon,
        Theme::RosePineDawn,
        Theme::Material,
        Theme::MaterialOcean,
        Theme::MaterialPalenight,
        Theme::MaterialLighter,
        Theme::SolarizedDark,
        Theme::SolarizedLight,
        Theme::GithubDark,
        Theme::GithubLight,
        Theme::AyuDark,
        Theme::AyuMirage,
        Theme::AyuLight,
        Theme::NightOwl,
        Theme::NightOwlLight,
        Theme::Moonlight,
        Theme::Projectious,
    ];

    const ALL_PROMPTS: &[StarshipPreset] = &[
        StarshipPreset::Default,
        StarshipPreset::Plain,
        StarshipPreset::Minimal,
        StarshipPreset::NerdFont,
        StarshipPreset::Pastel,
        StarshipPreset::PastelPowerline,
        StarshipPreset::Bracketed,
        StarshipPreset::Arrow,
    ];

    /// No theme leaves a palette placeholder string ("#" plus all caps) in any
    /// generated artifact. Catches forgotten substitutions in starship presets,
    /// yazi themes, vim colorschemes, gitconfig, and lazygit.
    #[test]
    fn every_theme_renders_without_placeholders() {
        // Tokens we use across format!() strings — any leak indicates a bug.
        let placeholders = [
            "{bg}",
            "{fg}",
            "{accent}",
            "{green}",
            "{red}",
            "{yellow}",
            "{orange}",
            "{cyan}",
            "{muted}",
            "{surface}",
            "{magenta}",
        ];
        for theme in ALL_THEMES {
            let artifacts: Vec<(&str, String)> = vec![
                ("vim_aibox_colorscheme", vim_aibox_colorscheme(theme)),
                ("yazi_theme", yazi_theme_with_separator(theme, "rounded")),
                ("lazygit_theme", lazygit_theme(theme)),
                ("gitconfig_with_delta", gitconfig_with_delta(theme)),
                ("theme_env_script", theme_env_script(theme)),
                ("lnav_config", lnav_config(theme)),
                (
                    "tmux_powerkit_custom_theme",
                    tmux_powerkit_custom_theme(theme),
                ),
            ];
            for (name, body) in artifacts {
                for placeholder in &placeholders {
                    assert!(
                        !body.contains(placeholder),
                        "theme {theme}: {name} leaked placeholder {placeholder}:\n{body}"
                    );
                }
            }
            for preset in ALL_PROMPTS {
                let body = starship_config(preset, theme);
                for placeholder in &placeholders {
                    assert!(
                        !body.contains(placeholder),
                        "theme {theme} preset {preset}: starship_config leaked {placeholder}:\n{body}"
                    );
                }
                assert!(
                    !body.is_empty(),
                    "theme {theme} preset {preset}: starship_config returned empty body"
                );
            }
        }
    }

    /// Every theme's generated artifacts contain that theme's accent color
    /// somewhere it is actually used. Catches accidental cross-theme palette
    /// drift (e.g. a fallback that always emits gruvbox colors).
    #[test]
    fn every_theme_aligns_tools_to_its_accent() {
        for theme in ALL_THEMES {
            let (_bg, _fg, accent, _green, _red, _yellow, _orange, _cyan, _muted) =
                theme_palette(theme);
            let vim = vim_aibox_colorscheme(theme);
            assert!(
                vim.contains(accent),
                "theme {theme}: aibox.vim should embed accent {accent}, got:\n{vim}"
            );
            let yazi = yazi_theme_with_separator(theme, "rounded");
            assert!(
                yazi.contains(accent),
                "theme {theme}: yazi theme.toml should embed accent {accent}"
            );
            let starship = starship_config(&StarshipPreset::Default, theme);
            assert!(
                starship.contains(accent),
                "theme {theme}: default starship config should embed accent {accent}"
            );
            let powerkit = tmux_powerkit_custom_theme(theme);
            assert!(
                powerkit.contains(accent),
                "theme {theme}: powerkit theme should embed accent {accent}"
            );
        }
    }

    /// Preset-specific format expectations. Catches regressions where a preset
    /// rewrite drops its core module (`[directory]`, line-break shape, …).
    #[test]
    fn starship_presets_emit_their_expected_shape() {
        let theme = Theme::GruvboxDark;
        let default_body = starship_config(&StarshipPreset::Default, &theme);
        assert!(
            default_body.contains("directory") && default_body.contains("git_branch"),
            "default preset must include directory and git_branch modules:\n{default_body}"
        );

        let plain_body = starship_config(&StarshipPreset::Plain, &theme);
        // Plain preset must not use powerline glyphs (E0B0 left chevron).
        assert!(
            !plain_body.contains('\u{e0b0}'),
            "plain preset must be ASCII-only:\n{plain_body}"
        );

        for preset in [StarshipPreset::Pastel, StarshipPreset::PastelPowerline] {
            let body = starship_config(&preset, &theme);
            assert!(
                body.contains("pastel powerline preset"),
                "{preset} preset banner missing:\n{body}"
            );
            assert!(
                body.contains('\u{e0b0}'),
                "{preset} preset should use a powerline chevron:\n{body}"
            );
            assert!(
                !body.contains("$line_break"),
                "{preset} preset should render as a one-line prompt:\n{body}"
            );
        }
    }

    /// Every theme produces a Yazi theme that uses the current schema (Yazi 26
    /// requires url-based filetype rules and the [tabs]/[mode]/[status]/[git]
    /// sections; legacy keys must not survive).
    #[test]
    fn every_theme_yazi_uses_current_schema() {
        for theme in ALL_THEMES {
            let yazi = yazi_theme_with_separator(theme, "rounded");
            for required in [
                "[tabs]",
                "[mode]",
                "[status]",
                "[git]",
                "normal_main",
                "overall =",
                "url = \"*/\"",
            ] {
                assert!(
                    yazi.contains(required),
                    "theme {theme}: yazi theme should contain '{required}'"
                );
            }
            for legacy in [
                "tab_active",
                "mode_normal",
                "separator_open",
                "permissions_t",
                "[select]",
                "[completion]",
            ] {
                assert!(
                    !yazi.contains(legacy),
                    "theme {theme}: yazi theme must not contain legacy key '{legacy}'"
                );
            }
            assert!(
                !yazi.contains("{ name ="),
                "theme {theme}: Yazi 26 rejects name-only filetype rules"
            );
        }
    }

    #[test]
    fn powerkit_custom_theme_renders_palette_bg_for_every_theme() {
        // All 28 themes must emit `[background]=<their bg>` so chevrons land
        // on the exact aibox surface. Spot-check a representative roster.
        for (theme, expected_bg) in [
            (Theme::GruvboxDark, "#282828"),
            (Theme::GruvboxLight, "#FBF1C7"),
            (Theme::Projectious, "#0E1720"),
            (Theme::CatppuccinMocha, "#1E1E2E"),
            (Theme::TokyoNightDay, "#E1E2E7"),
            (Theme::Nord, "#2E3440"),
            (Theme::GithubLight, "#FFFFFF"),
        ] {
            let body = tmux_powerkit_custom_theme(&theme);
            assert!(
                body.contains(&format!("[background]=\"{expected_bg}\"")),
                "powerkit custom theme for {theme} must declare bg {expected_bg}, got:\n{body}"
            );
        }
    }
}
